# Candidat MS
spring.application.name=candidat-ms
server.port=8060
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Message temporaire (sera écrasé par le serveur)
welcome.message=Welcome to Candidat MS