spring.application.name=config-server
server.port=8888

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

# Config Server (mode native = fichiers locaux)
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/config

# (Optionnel) Git : décommentez si vous voulez utiliser un repo Git
# spring.cloud.config.server.git.uri=https://github.com/votre-repo.git